import axios from 'axios';

export class BhashiniClient {
  private apiKey: string | undefined;

  constructor() {
    this.apiKey = process.env.BHASHINI_API_KEY;
  }

  private offlineDict: Record<string, Record<string, string>> = {
    hi: {
      'Investigative Brief': 'जांच विवरण एवं केस रिपोर्ट',
      'SANDHAN - Evidence-Aware Cyber Fraud Investigation Engine': 'संधान - साक्ष्य-आधारित साइबर धोखाधड़ी जांच इंजन',
      'Primary Fraud Path': 'मुख्य धोखाधड़ी मार्ग (फंड ट्रेल)',
      'Top Investigative Leads': 'शीर्ष जांच सुराग एवं संदिग्ध संस्थाएं',
      'Evidence Chain': 'साक्ष्य श्रृंखला एवं हैश सत्यापन',
      'Case Summary': 'मामले का सारांश',
      'Total Financial Loss': 'कुल वित्तीय हानि',
      'Correlated Entities': 'संबद्ध संस्थाएं',
      'Time Window': 'समय सीमा (30 मिनट)',
      'Shared Device (IMEI)': 'साझा डिवाइस (आईएमईआई)',
      'Shared Network (IP)': 'साझा नेटवर्क (आईपी)',
      'Risk Score': 'जोखिम स्कोर',
      'Confidence Level': 'विश्वसनीयता स्तर',
      'Primary Signal': 'मुख्य संकेत',
      'SIM switching': 'सिम परिवर्तन (SIM Switching)',
      'Device reuse': 'डिवाइस पुनरुपयोग',
      'Rapid fund movement': 'त्वरित धन हस्तांतरण',
      'Multi-hop routing': 'मल्टी-हॉप फंड रूटिंग',
      'IP reuse across sessions': 'विभिन्न सत्रों में आईपी पुनरुपयोग',
      'Generated by SANDHAN': 'संधान (SANDHAN) द्वारा निर्मित रिपोर्ट',
      'Dashboard': 'डैशबोर्ड',
      'Ingest Data': 'डेटा प्रविष्टि',
      'Graph Visualization': 'ग्राफ विज़ुअलाइज़ेशन',
      'Audit Log': 'ऑडिट लॉग',
      'Log Out': 'लॉग आउट',
    },
    mr: {
      'Investigative Brief': 'तपास अहवाल आणि केस सारांश',
      'Primary Fraud Path': 'मुख्य फसवणूक मार्ग',
      'Top Investigative Leads': 'प्रमुख संशयित संस्था',
      'Risk Score': 'धोका गुणक',
    },
    ta: {
      'Investigative Brief': 'விசாரணை அறிக்கை',
      'Primary Fraud Path': 'முதன்மை மோசடி பாதை',
    },
    te: {
      'Investigative Brief': 'విచారణ నివేదిక',
      'Primary Fraud Path': 'ప్రధాన మోసపు మార్గం',
    },
    kn: {
      'Investigative Brief': 'ತನಿಖಾ ವರದಿ',
      'Primary Fraud Path': 'ಮುಖ್ಯ ವಂಚನೆ ಮಾರ್ಗ',
    },
  };

  async translate(text: string, sourceLang: string, targetLang: string): Promise<string> {
    if (targetLang === 'en') return text;

    if (!this.apiKey) {
      const dict = this.offlineDict[targetLang] || this.offlineDict['hi'];
      let translated = text;

      // Replace known phrases
      for (const [en, target] of Object.entries(dict)) {
        const regex = new RegExp(en, 'gi');
        translated = translated.replace(regex, target);
      }

      // If full text was not matched in dict, replace key headings and labels
      if (translated === text && targetLang === 'hi') {
        translated = text
          .replace(/Investigative Brief/g, 'जांच विवरण')
          .replace(/Evidence/g, 'साक्ष्य')
          .replace(/Risk/g, 'जोखिम')
          .replace(/Confidence/g, 'विश्वसनीयता')
          .replace(/Suspect/g, 'संदिग्ध')
          .replace(/Phone/g, 'फ़ोन')
          .replace(/Account/g, 'खाता')
          .replace(/Device/g, 'उपकरण')
          .replace(/Analysis/g, 'विश्लेषण');
      }

      return translated;
    }
    
    try {
      const response = await axios.post('https://meity-auth.ulcacontrib.org/ulca/apis/v0/model/getModelsPipeline', {
        pipelineTasks: [
          {
            taskType: "translation",
            config: {
              language: {
                sourceLanguage: sourceLang,
                targetLanguage: targetLang
              }
            }
          }
        ],
        inputData: {
          input: [{ source: text }]
        }
      }, {
        headers: {
          'Authorization': this.apiKey
        }
      });
      return response.data?.pipelineResponse?.[0]?.output?.[0]?.target || text;
    } catch (e) {
      console.error('Bhashini translate error', e);
      return text;
    }
  }

  async asr(audioBase64: string, lang: string): Promise<string> {
    if (!this.apiKey) {
      return "Mock transcription of audio in " + lang;
    }
    return "Transcribed audio text in " + lang;
  }

  async translateBatch(texts: string[], targetLang: string): Promise<string[]> {
    return Promise.all(texts.map(t => this.translate(t, 'en', targetLang)));
  }
}
