import { CaseGraph, RiskScore, InvestigativeLead, EvidenceFile } from '../types';

export function generateBrief(graph: CaseGraph, scores: RiskScore[], leads: InvestigativeLead[], evidenceFiles: EvidenceFile[], anchorTime: Date): string {
  const html = `
    <div style="font-family: Arial, sans-serif; color: #333;">
      <h1 style="color: #002D62; border-bottom: 2px solid #FF8C00;">SANDHAN | संधान Case Brief</h1>
      <p>Generated on: ${new Date().toLocaleString()}</p>
      
      <h2 style="color: #002D62;">Case Summary</h2>
      <ul>
        <li>Anchor Time: ${anchorTime.toLocaleString()}</li>
        <li>Entities Analyzed: ${graph.nodes.size}</li>
        <li>Relationships Identified: ${graph.edges.size}</li>
      </ul>

      <h2 style="color: #002D62;">Primary Fraud Path</h2>
      <p>Victim &rarr; UPI &rarr; Mule &rarr; Intermediary &rarr; IMEI &rarr; IP</p>
      
      <h2 style="color: #002D62;">Top Investigative Leads</h2>
      <table border="1" cellpadding="5" style="border-collapse: collapse; width: 100%;">
        <tr style="background-color: #002D62; color: white;">
          <th>Entity</th>
          <th>Type</th>
          <th>Risk Score</th>
          <th>Top Signal</th>
        </tr>
        ${leads.map(lead => `
          <tr>
            <td>${lead.entity.value}</td>
            <td>${lead.entity.type}</td>
            <td>${lead.risk_score}</td>
            <td>${lead.top_signal}</td>
          </tr>
        `).join('')}
      </table>
      
      <h2 style="color: #002D62;">Evidence Chain</h2>
      <table border="1" cellpadding="5" style="border-collapse: collapse; width: 100%;">
        <tr style="background-color: #002D62; color: white;">
          <th>File Name</th>
          <th>Type</th>
          <th>SHA-256 Hash</th>
        </tr>
        ${evidenceFiles.map(file => `
          <tr>
            <td>${file.file_name}</td>
            <td>${file.file_type}</td>
            <td style="font-family: monospace; font-size: 0.9em;">${file.sha256_hash}</td>
          </tr>
        `).join('')}
      </table>
      
      <footer style="margin-top: 20px; font-size: 0.8em; text-align: center; color: #666;">
        Generated by SANDHAN | संधान
      </footer>
    </div>
  `;
  
  return html;
}

export function generateHtmlReport(graph: CaseGraph, scores: RiskScore[], leads: InvestigativeLead[], evidenceFiles: EvidenceFile[], anchorTime: Date): string {
  const brief = generateBrief(graph, scores, leads, evidenceFiles, anchorTime);
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>SANDHAN Case Brief</title>
      </head>
      <body>
        ${brief}
      </body>
    </html>
  `;
}
