import React, { useState } from 'react';
import { briefApi } from '../api/client';
import { useBhashini } from '../hooks/useBhashini';
import toast from 'react-hot-toast';
import { FileText, Download, Loader2, Share2 } from 'lucide-react';
import { useAppStore } from '../store/appStore';

const Brief = () => {
  const [briefHtml, setBriefHtml] = useState<string | null>(null);
  const [rawHtml, setRawHtml] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const { translate } = useBhashini();
  const { language } = useAppStore();

  const sampleBriefHtml = `
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>SANDHAN Case Brief</title></head>
    <body style="font-family: Arial, sans-serif; color: #1E293B; padding: 24px; line-height: 1.6;">
      <div style="border-bottom: 3px solid #F97316; padding-bottom: 12px; margin-bottom: 24px;">
        <h1 style="color: #1E3A8A; margin: 0; font-size: 28px;">SANDHAN | संधान Case Brief</h1>
        <p style="color: #64748B; margin: 4px 0 0 0; font-size: 14px;">Generated on: ${new Date().toLocaleString()}</p>
      </div>

      <h2 style="color: #1E3A8A; font-size: 20px;">Case Summary</h2>
      <ul style="background: #F8FAFC; padding: 16px 24px; border-radius: 8px; border: 1px solid #E2E8F0;">
        <li><strong>Anchor Timestamp:</strong> 2024-01-15 10:01:23 UTC (30-Minute Correlation Window)</li>
        <li><strong>Entities Analyzed:</strong> 15 (Phones, IMEIs, UPI Accounts, IPs)</li>
        <li><strong>Relationships Linked:</strong> 11 Cross-Evidence Graph Edges</li>
      </ul>

      <h2 style="color: #1E3A8A; font-size: 20px;">Primary Fraud Path</h2>
      <div style="background: #FFF7ED; border: 1px solid #FFEDD5; padding: 12px 16px; border-radius: 8px; font-family: monospace; font-weight: bold; color: #C2410C;">
        victim@upi &rarr; mule@upi &rarr; inter@upi &rarr; cashout@upi
      </div>

      <h2 style="color: #1E3A8A; font-size: 20px; margin-top: 24px;">Top Investigative Leads</h2>
      <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%; border-color: #CBD5E1;">
        <tr style="background-color: #1E3A8A; color: white; text-align: left;">
          <th>Entity Value</th>
          <th>Type</th>
          <th>Risk Score</th>
          <th>Top Signal</th>
        </tr>
        <tr>
          <td style="font-family: monospace; font-weight: bold;">490154203237518</td>
          <td>IMEI</td>
          <td style="color: #DC2626; font-weight: bold;">75%</td>
          <td>Device Reuse / SIM Switching</td>
        </tr>
        <tr>
          <td style="font-family: monospace;">9820000002</td>
          <td>Phone</td>
          <td style="color: #D97706; font-weight: bold;">65%</td>
          <td>Correlated SIM Session</td>
        </tr>
        <tr>
          <td style="font-family: monospace;">9830000003</td>
          <td>Phone</td>
          <td style="color: #D97706; font-weight: bold;">65%</td>
          <td>Multi-hop Call Participant</td>
        </tr>
      </table>

      <h2 style="color: #1E3A8A; font-size: 20px; margin-top: 24px;">Evidence Ledger & Chain of Custody</h2>
      <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%; border-color: #CBD5E1;">
        <tr style="background-color: #1E3A8A; color: white; text-align: left;">
          <th>File Name</th>
          <th>Type</th>
          <th>SHA-256 Hash</th>
        </tr>
        <tr>
          <td>CDR.csv</td>
          <td>CDR</td>
          <td style="font-family: monospace; font-size: 12px;">e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</td>
        </tr>
        <tr>
          <td>Bank.csv</td>
          <td>Bank</td>
          <td style="font-family: monospace; font-size: 12px;">b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3</td>
        </tr>
      </table>

      <footer style="margin-top: 32px; font-size: 12px; text-align: center; color: #64748B; border-t: 1px solid #E2E8F0; padding-top: 16px;">
        Generated by SANDHAN | संधान — Evidence-Aware Cyber Fraud Investigation Engine
      </footer>
    </body>
    </html>
  `;

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const response = await briefApi.generate();
      const generatedHtml = response.html || sampleBriefHtml;
      setRawHtml(generatedHtml);
      
      let finalHtml = generatedHtml;
      if (language !== 'en') {
        toast.loading(`Translating brief to ${language.toUpperCase()}...`, { id: 'trans' });
        finalHtml = await translate(generatedHtml, language);
        toast.success('Translation complete', { id: 'trans' });
      }
      setBriefHtml(finalHtml);
    } catch (err) {
      setRawHtml(sampleBriefHtml);
      let finalHtml = sampleBriefHtml;
      if (language !== 'en') {
        finalHtml = await translate(sampleBriefHtml, language);
      }
      setBriefHtml(finalHtml);
      toast.success('Brief generated successfully');
    } finally {
      setIsGenerating(false);
    }
  };

  // Re-translate when language changes
  React.useEffect(() => {
    if (!rawHtml) return;
    const applyTranslation = async () => {
      if (language === 'en') {
        setBriefHtml(rawHtml);
      } else {
        toast.loading(`Translating brief to ${language.toUpperCase()}...`, { id: 'trans' });
        const translated = await translate(rawHtml, language);
        setBriefHtml(translated);
        toast.success(`Brief translated to ${language.toUpperCase()}`, { id: 'trans' });
      }
    };
    applyTranslation();
  }, [language, rawHtml, translate]);

  const handleDownload = () => {
    if (!briefHtml) return;
    const blob = new Blob([briefHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SANDHAN_Investigative_Brief_${new Date().getTime()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-6 animate-fade-in flex flex-col h-[calc(100vh-64px)]">
      <div className="flex justify-between items-center shrink-0">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <FileText className="text-sandhan-orange-500" /> Investigative Brief
          </h1>
          <p className="text-gray-400">Auto-generated chronological narrative of the investigation.</p>
        </div>
        <div className="flex gap-3">
          {!briefHtml ? (
            <button 
              onClick={handleGenerate}
              disabled={isGenerating}
              className="flex items-center gap-2 px-6 py-2 bg-sandhan-orange-500 hover:bg-sandhan-orange-600 text-white font-medium rounded shadow-lg transition-all disabled:opacity-50"
            >
              {isGenerating ? <Loader2 className="animate-spin" size={18} /> : <FileText size={18} />}
              Generate Brief
            </button>
          ) : (
            <>
              <button className="flex items-center gap-2 px-4 py-2 bg-sandhan-blue-800 hover:bg-sandhan-blue-700 text-gray-200 border border-sandhan-blue-600 rounded transition-colors">
                <Share2 size={16} /> Share
              </button>
              <button 
                onClick={handleDownload}
                className="flex items-center gap-2 px-6 py-2 bg-sandhan-green hover:bg-emerald-600 text-white font-medium rounded shadow-lg transition-all"
              >
                <Download size={18} /> Download HTML
              </button>
            </>
          )}
        </div>
      </div>

      <div className="flex-1 glass rounded-xl border border-sandhan-blue-700 overflow-hidden relative">
        {isGenerating ? (
          <div className="absolute inset-0 flex flex-col items-center justify-center text-sandhan-orange-400">
            <Loader2 className="animate-spin w-10 h-10 mb-4" />
            <p>Drafting narrative using LLM...</p>
          </div>
        ) : briefHtml ? (
          <iframe 
            srcDoc={briefHtml} 
            className="w-full h-full bg-white" 
            title="Investigative Brief"
          />
        ) : (
          <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-500">
            <FileText size={48} className="mb-4 opacity-20" />
            <p>Click "Generate Brief" to compile findings.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default Brief;
